"""empty message

Revision ID: 877a19e70ecf
Revises: 6f785071517d
Create Date: 2023-04-16 20:48:54.156258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877a19e70ecf'
down_revision = '6f785071517d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imdb_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_column('imdb_id')

    # ### end Alembic commands ###
